service: beerobot

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-north-1
  memorySize: 128
  timeout: 10

functions:
  handleEvent:
    handler: src/handler.run
    events:
      - http:
          path: /
          method: post
  slackDelete:
    handler: src/slack-delete-handler.run
    reservedConcurrency: 1
